"use client";

import { useEffect, useRef, useState } from "react";
import { RefreshCw, X } from "lucide-react";
import { AdminConfidenceBadge, AdminEmptyState, AdminStatusBadge, CorrectionDiff } from "@/components/admin/AdminUI";
import { getAdminFieldIntelligenceDetail } from "@/lib/admin/client";
import type { AdminFieldIntelligenceDetail, AdminFieldOccurrenceExample } from "@/lib/admin/types";

type Tab = "overview" | "status" | "differences" | "review";
const display = (value: string | null) => value === null || value === "" ? "Unavailable" : value;

export function FieldIntelligenceDrawer({fieldKey,onClose}:{fieldKey:string;onClose:()=>void}) {
  const [data,setData]=useState<AdminFieldIntelligenceDetail|null>(null);
  const [error,setError]=useState<string|null>(null);
  const [retryKey,setRetryKey]=useState(0);
  const [tab,setTab]=useState<Tab>("overview");
  const closeRef=useRef<HTMLButtonElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;closeRef.current?.focus();const close=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose()};window.addEventListener("keydown",close);return()=>{window.removeEventListener("keydown",close);previous?.focus()}},[onClose]);
  useEffect(()=>{const controller=new AbortController();getAdminFieldIntelligenceDetail(fieldKey,controller.signal).then((result)=>{setData(result);setError(null)}).catch((reason:unknown)=>{if(reason instanceof DOMException&&reason.name==="AbortError")return;setError(reason instanceof Error?reason.message:"Field details could not be loaded.")});return()=>controller.abort()},[fieldKey,retryKey]);
  return <div className="admin-drawer-overlay" role="presentation" onMouseDown={onClose}><aside className="admin-drawer" role="dialog" aria-modal="true" aria-label="Field intelligence details" onMouseDown={(event)=>event.stopPropagation()}><header className="admin-drawer-header"><div><h2>{data?.fieldLabel??fieldKey}</h2><p>{data?.fieldKey??"Loading field analytics"}</p></div><button ref={closeRef} className="admin-icon-button" onClick={onClose} aria-label="Close field details"><X size={15}/></button></header><div className="admin-drawer-body">{!data&&!error?<div className="admin-overview-loading" aria-label="Loading field details"><div className="admin-skeleton admin-skeleton-title"/><div className="admin-skeleton admin-skeleton-chart"/></div>:error?<div className="admin-overview-error"><AdminEmptyState title="Field details could not be loaded" description={error}/><button className="admin-button admin-button-primary" onClick={()=>setRetryKey((value)=>value+1)}><RefreshCw size={13}/>Retry</button></div>:data?<><div className="admin-filter-bar" role="tablist" aria-label="Field intelligence sections">{(["overview","status","differences","review"] as Tab[]).map((item)=><button key={item} role="tab" aria-selected={tab===item} className={`admin-button ${tab===item?"admin-button-primary":""}`} onClick={()=>setTab(item)}>{item==="differences"?"Current Differences":item==="review"?"Review Examples":item[0].toUpperCase()+item.slice(1)}</button>)}</div>{tab==="overview"?<div className="admin-detail-grid"><Detail label="Occurrences" value={data.metrics.occurrenceCount}/><Detail label="Documents" value={data.metrics.documentCount}/><Detail label="Coverage" value={`${data.metrics.coverageRate}%`}/><Detail label="Average confidence" value={data.metrics.averageConfidence===null?"Unavailable":<AdminConfidenceBadge value={data.metrics.averageConfidence}/>}/><Detail label="Needs-review rate" value={`${data.metrics.needsReviewRate}%`}/><Detail label="Missing rate" value={`${data.metrics.missingRate}%`}/><Detail label="Different from AI" value={`${data.metrics.editedFieldCount} (${data.metrics.editedFieldRate}%)`}/><Detail label="Main issue" value={data.metrics.primaryIssue.replace("_"," ")}/></div>:null}{tab==="status"?<><div className="admin-detail-grid"><Detail label="Valid" value={data.statusDistribution.valid}/><Detail label="Warning" value={data.statusDistribution.warning}/><Detail label="Review status" value={data.statusDistribution.review}/><Detail label="Missing" value={data.statusDistribution.missing}/><Detail label="Needs-review flag" value={data.statusDistribution.needsReview}/></div><p className="admin-drawer-note">Needs-review is an overlapping flag and is not added to the mutually exclusive field status total.</p></>:null}{tab==="differences"?<ExampleList examples={data.differenceExamples} mode="difference"/>:null}{tab==="review"?<ExampleList examples={data.reviewExamples} mode="review"/>:null}</>:null}</div></aside></div>;
}

function ExampleList({examples,mode}:{examples:AdminFieldOccurrenceExample[];mode:"difference"|"review"}) { return <><p className="admin-drawer-note">{mode==="difference"?"These are current differences from original AI output. Historical correction events and edit timelines are not available.":"Examples are selected from persisted review flags and problematic field statuses. No correction reason is inferred."}</p>{examples.length?<div className="admin-field-detail-list">{examples.map((example)=><article className="admin-field-detail" key={example.fieldId}><header><strong>{example.fileName??example.documentId.slice(0,8)}</strong><AdminStatusBadge status={example.fieldStatus}/></header>{mode==="difference"?<CorrectionDiff before={display(example.originalAiValue)} after={display(example.currentValue)}/>:<div className="admin-detail-grid"><Detail label="Current value" value={display(example.currentValue)}/><Detail label="Confidence" value={example.confidence===null?"Unavailable":`${example.confidence}%`}/></div>}<div className="admin-field-meta"><span>AWB {example.awbNumber??"Unavailable"}</span><span>Document {example.documentId.slice(0,8)}</span><span>Document status: {example.documentStatus}</span><span>{example.needsReview?"Needs review":"No review flag"}</span></div></article>)}</div>:<AdminEmptyState title="No matching document examples are available for this field" description={mode==="difference"?"No current values differ from their original AI output.":"No persisted review examples are available."}/>}</> }
function Detail({label,value}:{label:string;value:React.ReactNode}) { return <div className="admin-detail-item"><span>{label}</span><strong>{value}</strong></div> }
