"use client";

import { useEffect, useState } from "react";
import { X } from "lucide-react";
import type { AuditDocument, Correction, EvaluationRun, FieldMetric } from "@/lib/admin/types";
import { AdminConfidenceBadge, AdminStatusBadge, CorrectionDiff } from "../AdminUI";

function Drawer({title,subtitle,onClose,children}:{title:string;subtitle:string;onClose:()=>void;children:React.ReactNode}){
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose()};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[onClose]);
  return <div className="admin-drawer-overlay" role="presentation" onMouseDown={onClose}><aside className="admin-drawer" role="dialog" aria-modal="true" aria-label={title} onMouseDown={event=>event.stopPropagation()}><header className="admin-drawer-header"><div><h2>{title}</h2><p>{subtitle}</p></div><button className="admin-icon-button" onClick={onClose} aria-label="Close details"><X size={15}/></button></header><div className="admin-drawer-body">{children}</div></aside></div>;
}
const Detail=({label,value}:{label:string;value:React.ReactNode})=><div className="admin-detail-item"><span>{label}</span><strong>{value}</strong></div>;

export function RunDetailDrawer({run,onClose}:{run:EvaluationRun;onClose:()=>void}){return <Drawer title={run.name} subtitle={`${run.startedAt} → ${run.completedAt}`} onClose={onClose}><div className="admin-detail-grid"><Detail label="Documents" value={run.documentCount}/><Detail label="Model" value={run.modelVersion}/><Detail label="Success rate" value={`${run.successRate}%`}/><Detail label="Correction rate" value={`${run.correctionRate}%`}/><Detail label="Average time" value={`${run.averageProcessingTime}s`}/><Detail label="Status" value={<AdminStatusBadge status={run.status}/>}/></div><button className="admin-button admin-button-primary" disabled>Backend integration pending</button></Drawer>}
export function FieldDetailDrawer({field,onClose}:{field:FieldMetric;onClose:()=>void}){return <Drawer title={field.name} subtitle="Field intelligence drill-down" onClose={onClose}><div className="admin-detail-grid"><Detail label="Confidence" value={<AdminConfidenceBadge value={field.confidence}/>}/><Detail label="Correction rate" value={`${field.correctionRate}%`}/><Detail label="Missing rate" value={`${field.missingRate}%`}/><Detail label="Validation failure" value={`${field.validationRate}%`}/></div><Detail label="Most common issue" value={field.issue}/><button className="admin-button admin-button-primary" disabled>Backend integration pending</button></Drawer>}
export function CorrectionDetailDrawer({correction,onClose}:{correction:Correction;onClose:()=>void}){return <Drawer title={`${correction.documentId} · ${correction.field}`} subtitle="Correction detail" onClose={onClose}><CorrectionDiff before={correction.original} after={correction.corrected}/><div className="admin-detail-grid"><Detail label="Confidence" value={`${correction.confidence}%`}/><Detail label="Change type" value={correction.type}/><Detail label="Reviewer" value={correction.reviewer}/><Detail label="Model" value={correction.modelVersion}/></div></Drawer>}
export function DocumentDetailDrawer({document,onClose}:{document:AuditDocument;onClose:()=>void}){const [tab,setTab]=useState("overview");return <Drawer title={document.id} subtitle={document.file} onClose={onClose}><div className="admin-filter-bar">{["overview","fields","corrections","timeline"].map(item=><button key={item} className={`admin-button ${tab===item?"admin-button-primary":""}`} onClick={()=>setTab(item)}>{item}</button>)}</div>{tab==="overview"?<div className="admin-detail-grid"><Detail label="Company" value={document.company}/><Detail label="AWB number" value={document.awbNumber}/><Detail label="Model" value={document.modelVersion}/><Detail label="Status" value={<AdminStatusBadge status={document.status}/>}/><Detail label="Fields extracted" value={document.fieldsExtracted}/><Detail label="Processing time" value={`${document.processingTime}s`}/></div>:<div className="admin-empty-state"><strong>{tab[0].toUpperCase()+tab.slice(1)}</strong><span>Detailed backend records will be connected in Phase 2.</span></div>}</Drawer>}
