import type { AdminPerformanceDocumentItem, AdminPerformanceDocumentListResponse, AdminPerformanceResponse } from "./types.ts";
import type { AdminDocumentRow, AdminFieldRow } from "./server/repository.ts";
import type { AdminPerformanceDocumentQuery } from "./server/validation.ts";
// @ts-expect-error Node's strip-types test runner requires explicit TypeScript extensions.
import { average, boundedPercent, validConfidencePercentages, validProcessingTimes } from "./metrics.ts";
// @ts-expect-error Node's strip-types test runner requires explicit TypeScript extensions.
import { getAdminStatusTone } from "./status.ts";
// @ts-expect-error Node's strip-types test runner requires explicit TypeScript extensions.
import { timingMetricsFromSummary } from "../awb/timingMetrics.ts";

const round = (value: number) => Math.round(value * 10) / 10;
export function median(values: number[]) { if (!values.length) return null; const sorted = [...values].sort((a, b) => a - b); const middle = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[middle] : (sorted[middle - 1] + sorted[middle]) / 2; }
// Nearest-rank percentile: rank = ceil(p * N), using the 1-based ranked observation.
export function nearestRankPercentile(values: number[], percentile: number) { if (!values.length) return null; const sorted = [...values].sort((a, b) => a - b); return sorted[Math.max(0, Math.ceil(percentile * sorted.length) - 1)]; }
export function processingSeconds(value: number | null) { const valid = validProcessingTimes([value]); return valid.length ? valid[0] / 1000 : null; }

const buckets = [
  { key: "under_10", label: "Under 10 seconds", minimumSeconds: null, maximumSeconds: 10, match: (value: number) => value < 10 },
  { key: "10_20", label: "10–20 seconds", minimumSeconds: 10, maximumSeconds: 20, match: (value: number) => value >= 10 && value < 20 },
  { key: "20_30", label: "20–30 seconds", minimumSeconds: 20, maximumSeconds: 30, match: (value: number) => value >= 20 && value < 30 },
  { key: "30_45", label: "30–45 seconds", minimumSeconds: 30, maximumSeconds: 45, match: (value: number) => value >= 30 && value < 45 },
  { key: "45_60", label: "45–60 seconds", minimumSeconds: 45, maximumSeconds: 60, match: (value: number) => value >= 45 && value < 60 },
  { key: "over_60", label: "60 seconds or more", minimumSeconds: 60, maximumSeconds: null, match: (value: number) => value >= 60 },
];
export function buildProcessingDistribution(seconds: number[]) { return buckets.map(({ match, ...bucket }) => { const count = seconds.filter(match).length; return { ...bucket, count, percentage: boundedPercent(count, seconds.length) }; }); }

function groupFields(fields: AdminFieldRow[]) { const map = new Map<string, AdminFieldRow[]>(); for (const field of fields) { const group = map.get(field.document_id) ?? []; group.push(field); map.set(field.document_id, group); } return map; }
export function mapPerformanceDocument(document: AdminDocumentRow, fields: AdminFieldRow[]): AdminPerformanceDocumentItem {
  const confidences = validConfidencePercentages(fields.map((field) => field.confidence));
  const timing = timingMetricsFromSummary(document.summary);
  return { id: document.id, companyId: document.company_id ?? null, fileName: document.file_name || null, awbNumber: fields.find((field) => field.key === "awb_number")?.value?.trim() || null, status: document.status, processingTimeSeconds: processingSeconds(document.processing_time_ms), ocrTimeSeconds: processingSeconds(timing.extractorMs), aiTimeSeconds: processingSeconds(timing.llmMs), businessLogicTimeSeconds: processingSeconds(timing.businessLogicMs), totalLifecycleProcessingSeconds: processingSeconds(timing.totalMs), reviewSessionSeconds: processingSeconds(timing.activeReviewMs), uploadToIssueSeconds: processingSeconds(timing.uploadToIssueMs), correctedFieldsCount: timing.correctedFieldsCount, createdAt: document.created_at, updatedAt: document.updated_at, failureCategory: null, safeFailureMessage: document.status === "failed" ? "Processing failed. Detailed failure information is unavailable." : null, fieldCount: fields.length, averageConfidence: confidences.length ? round(average(confidences)) : null };
}

export function buildAdminPerformance(documents: AdminDocumentRow[], fields: AdminFieldRow[]): AdminPerformanceResponse {
  const fieldsByDocument = groupFields(fields); const seconds = documents.flatMap((document) => { const value = processingSeconds(document.processing_time_ms); return value === null ? [] : [value]; }); const sorted = [...seconds].sort((a, b) => a - b); const failed = documents.filter((document) => document.status === "failed"); const failedSamples = failed.filter((document) => processingSeconds(document.processing_time_ms) !== null).length;
  const daily = new Map<string, { total: number; samples: number; failed: number }>(); for (const document of documents) { const date = document.created_at.slice(0, 10); const group = daily.get(date) ?? { total: 0, samples: 0, failed: 0 }; const value = processingSeconds(document.processing_time_ms); if (value !== null) { group.total += value; group.samples += 1; } if (document.status === "failed") group.failed += 1; daily.set(date, group); }
  const statusCounts = new Map<string, number>(); for (const document of documents) statusCounts.set(document.status, (statusCounts.get(document.status) ?? 0) + 1);
  const timingRows = documents.map((document) => timingMetricsFromSummary(document.summary));
  const timingSeconds = (key: keyof ReturnType<typeof timingMetricsFromSummary>) => timingRows.flatMap((timing) => { const value = processingSeconds(typeof timing[key] === "number" ? timing[key] : null); return value === null ? [] : [value]; });
  const ocrSeconds = timingSeconds("extractorMs"); const aiSeconds = timingSeconds("llmMs"); const businessSeconds = timingSeconds("businessLogicMs"); const lifecycleSeconds = timingSeconds("totalMs"); const reviewSeconds = timingSeconds("activeReviewMs"); const uploadIssueSeconds = timingSeconds("uploadToIssueMs"); const issuedTiming = documents.filter((document) => document.status === "issued").map((document) => timingMetricsFromSummary(document.summary)); const corrections = issuedTiming.flatMap((timing) => timing.correctedFieldsCount === null ? [] : [timing.correctedFieldsCount]); const totalCorrectedFields = corrections.reduce((total, count) => total + count, 0); const avg = (values: number[]) => values.length ? round(average(values)) : null;
  const summary = { totalDocuments: documents.length, validProcessingSampleCount: seconds.length, missingOrInvalidProcessingTimeCount: documents.length - seconds.length, averageProcessingTimeSeconds: seconds.length ? round(average(seconds)) : null, medianProcessingTimeSeconds: median(seconds) === null ? null : round(median(seconds)!), p90ProcessingTimeSeconds: nearestRankPercentile(seconds, .9) === null ? null : round(nearestRankPercentile(seconds, .9)!), p95ProcessingTimeSeconds: nearestRankPercentile(seconds, .95) === null ? null : round(nearestRankPercentile(seconds, .95)!), fastestProcessingTimeSeconds: sorted.length ? round(sorted[0]) : null, slowestProcessingTimeSeconds: sorted.length ? round(sorted.at(-1)!) : null, failedDocumentCount: failed.length, failureRate: boundedPercent(failed.length, documents.length), failedDocumentProcessingSampleCount: failedSamples, failedDocumentMissingTimeCount: failed.length - failedSamples, averageOcrTimeSeconds: avg(ocrSeconds), averageAiTimeSeconds: avg(aiSeconds), averageBusinessLogicTimeSeconds: avg(businessSeconds), averageLifecycleProcessingSeconds: avg(lifecycleSeconds), averageReviewSessionSeconds: avg(reviewSeconds), medianReviewSessionSeconds: median(reviewSeconds) === null ? null : round(median(reviewSeconds)!), averageUploadToIssueSeconds: avg(uploadIssueSeconds), documentsWithReviewTiming: reviewSeconds.length, documentsMissingReviewTiming: documents.length - reviewSeconds.length, issuedDocumentCount: issuedTiming.length, totalCorrectedFields, averageCorrectionsPerIssuedDocument: corrections.length ? round(totalCorrectedFields / corrections.length) : null };
  const map = (document: AdminDocumentRow) => mapPerformanceDocument(document, fieldsByDocument.get(document.id) ?? []);
  return { summary, processingDistribution: buildProcessingDistribution(seconds), processingTrend: [...daily].filter(([, group]) => group.samples > 0 || group.failed > 0).sort(([a], [b]) => a.localeCompare(b)).map(([date, group]) => ({ date, averageProcessingTimeSeconds: group.samples ? round(group.total / group.samples) : null, sampleCount: group.samples, failedDocumentCount: group.failed })), statusDistribution: [...statusCounts].map(([status, value]) => ({ name: status.replace(/_/g, " "), value, tone: getAdminStatusTone(status) })), percentileComparison: [["Average", summary.averageProcessingTimeSeconds], ["Median", summary.medianProcessingTimeSeconds], ["P90", summary.p90ProcessingTimeSeconds], ["P95", summary.p95ProcessingTimeSeconds]].flatMap(([name, value]) => typeof value === "number" ? [{ name: String(name), value }] : []), slowestDocumentsPreview: documents.filter((document) => processingSeconds(document.processing_time_ms) !== null).sort((a, b) => Number(b.processing_time_ms) - Number(a.processing_time_ms)).slice(0, 5).map(map), failedDocumentsPreview: failed.sort((a, b) => b.updated_at.localeCompare(a.updated_at)).slice(0, 5).map(map), capabilities: { hasStageTimings: ocrSeconds.length > 0 || aiSeconds.length > 0 || businessSeconds.length > 0, hasRetryHistory: false, hasStructuredFailureCategories: false, hasSafeFailureMessages: false, hasModelVersion: false } };
}

export function buildAdminPerformanceDocumentList(documents: AdminDocumentRow[], fields: AdminFieldRow[], totalItems: number, query: AdminPerformanceDocumentQuery): AdminPerformanceDocumentListResponse {
  const fieldsByDocument = groupFields(fields);
  return { items: documents.map((document) => mapPerformanceDocument(document, fieldsByDocument.get(document.id) ?? [])), pagination: { page: query.page, pageSize: query.pageSize, totalItems, totalPages: Math.ceil(totalItems / query.pageSize) }, appliedFilters: { type: query.type, search: query.search, sortBy: query.sortBy, sortOrder: query.sortOrder } };
}
