"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ChevronLeft, ChevronRight, RefreshCw } from "lucide-react";
import { AdminBarChart, AdminDonutChart } from "@/components/admin/charts/AdminCharts";
import { AdminCard, AdminEmptyState, AdminMetricCard, AdminPageHeader, AdminStatusBadge, AdminTableWrap, AdminUnavailableNotice } from "@/components/admin/AdminUI";
import { getAdminPerformance, getAdminPerformanceDocuments } from "@/lib/admin/client";
import type { AdminPerformanceDocumentListResponse, AdminPerformanceResponse } from "@/lib/admin/types";
import { useAdminAnalyticsScope } from "@/components/admin/layout/AdminAnalyticsFilters";
import { formatDuration } from "@/lib/awb/timingMetrics";

const seconds = (value: number | null) =>
  formatDuration(value === null ? null : value * 1000);
function Loading() { return <div className="admin-overview-loading" aria-label="Loading performance analytics"><div className="admin-metric-grid">{Array.from({ length: 4 }, (_, index) => <div className="admin-skeleton admin-skeleton-metric" key={index}/>)}</div><div className="admin-grid-2"><div className="admin-skeleton admin-skeleton-chart"/><div className="admin-skeleton admin-skeleton-chart"/></div><div className="admin-skeleton admin-skeleton-chart"/></div>; }

function PerformanceTable({ title, description, data, page, setPage, emptyTitle }: { title: string; description: string; data: AdminPerformanceDocumentListResponse | null; page: number; setPage: React.Dispatch<React.SetStateAction<number>>; emptyTitle: string }) {
  return <AdminCard title={title} description={description}>{!data ? <div className="admin-skeleton admin-skeleton-chart"/> : data.items.length ? <><AdminTableWrap><table className="admin-table"><thead><tr><th>Document / File</th><th>Status</th><th>Extractor</th><th>AI / LLM</th><th>Business Logic</th><th>Total Processing</th><th>Active Review</th><th>Corrections</th><th>Upload to Issue</th><th>Inspect</th></tr></thead><tbody>{data.items.map((item) => <tr key={item.id}><td><strong>{item.id.slice(0, 8)}</strong><br/><small>{item.fileName ?? "Unavailable"}</small></td><td><AdminStatusBadge status={item.status}/></td><td>{seconds(item.ocrTimeSeconds)}</td><td>{seconds(item.aiTimeSeconds)}</td><td>{seconds(item.businessLogicTimeSeconds)}</td><td>{seconds(item.totalLifecycleProcessingSeconds ?? item.processingTimeSeconds)}</td><td>{seconds(item.reviewSessionSeconds)}</td><td>{item.correctedFieldsCount}</td><td>{seconds(item.uploadToIssueSeconds)}</td><td><Link className="admin-button" href={`/admin/documents?id=${item.id}`}>Open Document Audit</Link></td></tr>)}</tbody></table></AdminTableWrap><div className="admin-pagination"><span>Showing {(page - 1) * data.pagination.pageSize + 1}–{Math.min(page * data.pagination.pageSize, data.pagination.totalItems)} of {data.pagination.totalItems} documents</span><div><button onClick={() => setPage((value) => value - 1)} disabled={page <= 1} aria-label={`Previous ${title.toLowerCase()} page`}><ChevronLeft size={14}/></button><span className="admin-filter-chip">Page {page} of {Math.max(1, data.pagination.totalPages)}</span><button onClick={() => setPage((value) => value + 1)} disabled={page >= data.pagination.totalPages} aria-label={`Next ${title.toLowerCase()} page`}><ChevronRight size={14}/></button></div></div></> : <AdminEmptyState title={emptyTitle} description="No matching persisted documents are available."/>}</AdminCard>;
}

export function PerformanceClient() {
  const { scope, query } = useAdminAnalyticsScope();
  const [summary, setSummary] = useState<AdminPerformanceResponse | null>(null); const [slow, setSlow] = useState<AdminPerformanceDocumentListResponse | null>(null); const [failed, setFailed] = useState<AdminPerformanceDocumentListResponse | null>(null); const [error, setError] = useState<string | null>(null); const [retry, setRetry] = useState(0); const [input, setInput] = useState(""); const [search, setSearch] = useState(""); const [slowPage, setSlowPage] = useState(1); const [failedPage, setFailedPage] = useState(1); const [pageSize, setPageSize] = useState(10);
  useEffect(() => { const timer = window.setTimeout(() => { setSearch(input.trim()); setSlowPage(1); setFailedPage(1); }, 400); return () => window.clearTimeout(timer); }, [input]);
  useEffect(() => { const controller = new AbortController(); getAdminPerformance(scope, controller.signal).then((result) => { setSummary(result); setError(null); }).catch((reason: unknown) => { if (reason instanceof DOMException && reason.name === "AbortError") return; setError("The analytics request failed. Try again."); }); return () => controller.abort(); }, [query, retry, scope]);
  useEffect(() => { const controller = new AbortController(); Promise.all([getAdminPerformanceDocuments({ ...scope, type: "slow", page: slowPage, pageSize, search, sortBy: "processingTime", sortOrder: "desc" }, controller.signal), getAdminPerformanceDocuments({ ...scope, type: "failed", page: failedPage, pageSize, search, sortBy: "updatedAt", sortOrder: "desc" }, controller.signal)]).then(([slowResult, failedResult]) => { setSlow(slowResult); setFailed(failedResult); setError(null); }).catch((reason: unknown) => { if (reason instanceof DOMException && reason.name === "AbortError") return; setError("The analytics request failed. Try again."); }); return () => controller.abort(); }, [failedPage, pageSize, query, retry, scope, search, slowPage]);
  return <><AdminPageHeader title="Performance & Failures" description="Real total processing-time and persisted failure analytics."/>{!summary && !error ? <Loading/> : error ? <div className="admin-overview-error"><AdminEmptyState title="Data could not be loaded." description={error}/><button className="admin-button admin-button-primary" onClick={() => setRetry((value) => value + 1)}><RefreshCw size={13}/>Retry</button></div> : summary ? <>
    <div className="admin-metric-grid"><AdminMetricCard label="Average Processing Time" value={seconds(summary.summary.averageProcessingTimeSeconds)} note={`${summary.summary.validProcessingSampleCount} valid samples`} tone="info"/><AdminMetricCard label="Median Processing Time" value={seconds(summary.summary.medianProcessingTimeSeconds)} note="Middle valid duration" tone="info"/><AdminMetricCard label="P90 / P95" value={`${seconds(summary.summary.p90ProcessingTimeSeconds)} / ${seconds(summary.summary.p95ProcessingTimeSeconds)}`} note="Nearest-rank percentiles" tone="partial"/><AdminMetricCard label="Failed Documents" value={String(summary.summary.failedDocumentCount)} note={`${summary.summary.failureRate}% of ${summary.summary.totalDocuments} documents`} tone="danger"/></div>
    <div className="admin-metric-grid"><AdminMetricCard label="Valid Processing Samples" value={String(summary.summary.validProcessingSampleCount)} note={`${summary.summary.missingOrInvalidProcessingTimeCount} missing or invalid`} tone="info"/><AdminMetricCard label="Fastest Processing Time" value={seconds(summary.summary.fastestProcessingTimeSeconds)} note="Minimum valid total duration" tone="success"/><AdminMetricCard label="Slowest Processing Time" value={seconds(summary.summary.slowestProcessingTimeSeconds)} note="Maximum valid total duration" tone="partial"/><AdminMetricCard label="Failed Timing Samples" value={String(summary.summary.failedDocumentProcessingSampleCount)} note={`${summary.summary.failedDocumentMissingTimeCount} failed documents without timing`} tone="neutral"/></div>
    <div className="admin-metric-grid"><AdminMetricCard label="Average Extractor Time" value={seconds(summary.summary.averageOcrTimeSeconds)} note="Provider-reported document extraction samples" tone="info"/><AdminMetricCard label="Average AI / LLM Time" value={seconds(summary.summary.averageAiTimeSeconds)} note="Provider-reported verification samples" tone="info"/><AdminMetricCard label="Average Business Logic" value={seconds(summary.summary.averageBusinessLogicTimeSeconds)} note="Rules and normalization samples" tone="info"/><AdminMetricCard label="Average Total Processing" value={seconds(summary.summary.averageLifecycleProcessingSeconds)} note="Provider-reported extraction pipeline total" tone="info"/></div>
    <div className="admin-metric-grid"><AdminMetricCard label="Average Active Review" value={seconds(summary.summary.averageReviewSessionSeconds)} note={`${summary.summary.documentsWithReviewTiming} documents · 1m away / 3m inactivity grace`} tone="success"/><AdminMetricCard label="Median Active Review" value={seconds(summary.summary.medianReviewSessionSeconds)} note={`${summary.summary.documentsMissingReviewTiming} unavailable · interaction-based estimate`} tone="success"/><AdminMetricCard label="Total Corrected Fields" value={String(summary.summary.totalCorrectedFields)} note={`${summary.summary.averageCorrectionsPerIssuedDocument ?? "N/A"} average where final metrics exist`} tone="partial"/><AdminMetricCard label="Average Upload to Issue" value={seconds(summary.summary.averageUploadToIssueSeconds)} note={`${summary.summary.issuedDocumentCount} issued documents`} tone="info"/></div>
    <div className="admin-grid-2"><AdminCard title="Processing-Time Distribution" description={`Number of documents in each total processing-time range. Includes ${summary.summary.validProcessingSampleCount} valid timing samples; null or invalid timing is excluded.`}><div role="img" aria-label={`Processing-time distribution for ${summary.summary.validProcessingSampleCount} valid samples`}><AdminBarChart data={summary.processingDistribution.map((bucket) => ({ name: bucket.label, value: bucket.count }))} categoryLabel="Total processing time range" valueLabel="Documents"/></div></AdminCard><AdminCard title="Percentile Comparison" description="Total processing-time statistics for valid timing samples. P90/P95 are nearest-rank completion thresholds."><div role="img" aria-label="Average, median, P90 and P95 total processing time"><AdminBarChart unit="seconds" data={summary.percentileComparison} categoryLabel="Statistic" valueLabel="Processing time" tooltipNote={(item)=>item.name==="P90"?"90% of valid samples completed within this duration":item.name==="P95"?"95% of valid samples completed within this duration":undefined}/></div></AdminCard><AdminCard title="Daily Processing Trend" description="Average total processing time in seconds, grouped by document creation date. Null timing values are excluded."><div role="img" aria-label="Daily average processing time using document created date"><AdminBarChart unit="seconds" data={summary.processingTrend.filter((point) => point.averageProcessingTimeSeconds !== null).map((point) => ({ name: point.date.slice(5), value: point.averageProcessingTimeSeconds!, samples: point.sampleCount, failed: point.failedDocumentCount }))} categoryLabel="Document created date" valueLabel="Average processing time" tooltipNote={(item)=>`${item.samples} valid samples; ${item.failed} failed documents`}/></div></AdminCard><AdminCard title="Document Status Distribution" description="Number of persisted documents in each mutually exclusive workflow status."><div role="img" aria-label={`Status distribution across ${summary.summary.totalDocuments} documents`}><AdminDonutChart data={summary.statusDistribution} totalLabel="Documents"/></div></AdminCard></div>
    <div className="admin-grid-2"><AdminCard title="Lifecycle Timing" description="Per-document metrics are shown below" className="admin-card-compact"><p>Extractor, AI / LLM, business-logic, and total timings appear when the extraction provider supplies them. Active review, final correction count, and upload-to-issue timing are stored in the existing document summary. Missing values remain unavailable.</p></AdminCard><AdminCard title="Failure Details" description="Capability availability" className="admin-card-compact"><AdminUnavailableNotice title="Structured failure details are not available" description="Structured failure categories, retry history, model version, and safe stored failure messages are not currently available."/></AdminCard></div>
    <div className="admin-filter-bar"><label className="admin-sr-only" htmlFor="performance-search">Search performance documents</label><input id="performance-search" type="search" value={input} maxLength={100} onChange={(event) => setInput(event.target.value)} placeholder="Search document UUID, AWB, or file"/><label className="admin-sr-only" htmlFor="performance-page-size">Rows per page</label><select id="performance-page-size" value={pageSize} onChange={(event) => { setPageSize(Number(event.target.value)); setSlowPage(1); setFailedPage(1); }}>{[10, 25, 50, 100].map((size) => <option key={size} value={size}>{size} rows</option>)}</select></div>
    <PerformanceTable title="Slowest Documents" description="Valid total processing durations, slowest first" data={slow} page={slowPage} setPage={setSlowPage} emptyTitle="No valid processing-time samples are available"/>
    <PerformanceTable title="Failed Documents" description="Persisted failed status; detailed failure reasons are unavailable" data={failed} page={failedPage} setPage={setFailedPage} emptyTitle="No failed documents were found"/>
  </> : null}</>;
}
